version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: calculator-backend
    ports:
      - "5883:5883"
    environment:
      - HOST=0.0.0.0
      - PORT=5883
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5883"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - calculator-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: calculator-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5883
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge

volumes:
  logs:
